### PR TITLE
interval tweaks

### PR DESCRIPTION
**Pull request by mkalten**
* 1ms interval should further improve latency
* fix the unconventional fps interval

### CODE REVIEW

**Comment by floe** [comment]
Can you submit this (or change the PR) against the master branch? I'd like to have the change in both branches, and I can only properly merge master into dma-sg, not the other way round (at least AFAIK).

**Comment by mkalten** [comment]
well, the two branches are not the same, no?
in any case you can tweak the three values quicker yourself I guess ;)

**Comment by floe** [comment]
Yeah, good point :-)

**Comment by mkalten** [comment]
@floe for best results the POLL_INTERVAL should be 1ms actually,
since I still got lower frame rates than 60fps  with the current 4ms

**Comment by floe** [comment]
Would 3 ms also be sufficient? I'm a bit worried that the input_polldev thread will starve otherwise... but I'll give it a try this afternoon in any case.

**Comment by mkalten** [comment]
OK, if we have to bargain then I'll give you 2ms ;)
I tried a few values, and 2ms already provides continuous 60fps ...

And yes, actually I had troubles with one crash there, 
although I attributed that to the unstable kernel.

**Comment by mkalten** [comment]
well ... just as you predicted
any idea for working around this?

May 18 13:07:08 SUR40 kernel: [227327.002772] Hardware name: Samsung SUR40/SDNE-R78BA2-20, BIOS SDNE-R78BA2-2000 02/23/2012
May 18 13:07:08 SUR40 kernel: [227327.002776] Workqueue: events_freezable input_polled_device_work [input_polldev]
May 18 13:07:08 SUR40 kernel: [227327.002777]  000000000000049a ffff880061913c58 ffffffff817fb25d 0000000000000007
May 18 13:07:08 SUR40 kernel: [227327.002780]  0000000000000000 ffff880061913c98 ffffffff8107d967 ffff880061913c78
May 18 13:07:08 SUR40 kernel: [227327.002782]  ffff88004e66e400 ffff88005fd3acc8 0000000000000005 ffff88006f10a518
May 18 13:07:08 SUR40 kernel: [227327.002783] Call Trace:
May 18 13:07:08 SUR40 kernel: [227327.002789]  [<ffffffff817fb25d>] dump_stack+0x4c/0x6e
May 18 13:07:08 SUR40 kernel: [227327.002792]  [<ffffffff8107d967>] warn_slowpath_common+0x97/0xe0
May 18 13:07:08 SUR40 kernel: [227327.002794]  [<ffffffff8107d9ca>] warn_slowpath_null+0x1a/0x20
May 18 13:07:08 SUR40 kernel: [227327.002797]  [<ffffffffc065f854>] vb2_buffer_done+0x134/0x180 [videobuf2_core]
May 18 13:07:08 SUR40 kernel: [227327.002799]  [<ffffffffc00f3a71>] sur40_poll+0x701/0x7c0 [sur40]
May 18 13:07:08 SUR40 kernel: [227327.002804]  [<ffffffffc0410280>] ? alc269_fixup_hp_mute_led_mic2+0x40/0x50 [snd_hda_codec_realtek]
May 18 13:07:08 SUR40 kernel: [227327.002807]  [<ffffffffc032634b>] input_polled_device_work+0x1b/0x30 [input_polldev]
May 18 13:07:08 SUR40 kernel: [227327.002809]  [<ffffffff810971db>] process_one_work+0x14b/0x4a0
May 18 13:07:08 SUR40 kernel: [227327.002811]  [<ffffffff8109799b>] worker_thread+0x11b/0x3b0
May 18 13:07:08 SUR40 kernel: [227327.002813]  [<ffffffff81097880>] ? rescuer_thread+0x310/0x310
May 18 13:07:08 SUR40 kernel: [227327.002815]  [<ffffffff8109d509>] kthread+0xc9/0xe0
May 18 13:07:08 SUR40 kernel: [227327.002818]  [<ffffffff8109d440>] ? flush_kthread_worker+0x90/0x90
May 18 13:07:08 SUR40 kernel: [227327.002820]  [<ffffffff818081e2>] ret_from_fork+0x42/0x70
May 18 13:07:08 SUR40 kernel: [227327.002822]  [<ffffffff8109d440>] ? flush_kthread_worker+0x90/0x90

**Comment by mkalten** [comment]
actually I also get the "packet ID mismatch" quite often flooding the syslog,
although this happened to me already before the adjustment of the POLL_INTERVAL.

since this is a warning of somehow expected behaviour maybe this should be a debug output?

**Comment by floe** [comment]
The warning actually comes from `vb2_buffer_done`, which is outside my code - I'm just passing the buffers from userspace. IIRC this warning is triggered when the application tries a to still use a buffer that has already been unregistered, so it's not really related to the poll interval IMHO.

**Comment by floe** [comment]
As for the packet ID mismatch warning, I think that can be safely ignored as long as you only use the video stream or only use the touch input data. This is only relevant if you want to use both at the same time.

**Comment by mkalten** [comment]
OK, it seems that I have found the problem ... it is actually more serious than I though,
because sometime this also caused a system freeze now, when exiting a V4L app using the device.

I also found a fix, which eventually eliminates the error:

the final vb2_buffer_done in sur40_process_video should return a different state once the device was stopped, since apparently that part still can be executed once after the buffers were deleted. 

so defining a global state variable which is set to  VB2_BUF_STATE_DONE in sur40_start_streaming and the set to VB2_BUF_STATE_ERROR in  sur40_stop_streaming should do the job.

**Comment by floe** [comment]
I've pushed a quick-and-dirty fix by setting sequence to -1, can you give it a try?

**Comment by mkalten** [comment]
well, I did some further testing with more tweaks like that (see my fork)
and although I still get the kernel warning, there are no more freezes on exit
and that kernel warning seems to show up with other V4L2 drivers as well it seems ;)

**Pull request closed without merging**
