### PR TITLE
60fps update

### PR DESCRIPTION
**Pull request by mkalten**
* reduce POLL_INTERVAL to 4ms
* implement V4L frame size and frame rate query

### CODE REVIEW

**Comment by mkalten** [comment]
actually we might even reduce the POLL_INTERVAL to 1ms,
since this might reduce the latency to get the next frame by another 3ms

no idea though if this is good behaviour or if this may cause other problems

**Comment by floe** [comment]
I'll test this on Monday when I'm back in the lab. AFAIK the POLL_INTERVAL is just the delay before the next request is started; if the hardware isn't ready yet, it won't make a difference as the thread will just sleep longer. BTW, why isn't the frame interval just 1/60, but instead 16/960?

**Comment by mkalten** [comment]
I guess my intention was to depict the 16ms frame duration

**Comment by floe** [comment]
I've had a look at the other V4L drivers, they all use 1/x, so that's probably the convention to use. But I can fix that when I submit the kernel patch.

**Pull request merged**
